=== oleggye/Java11_16_Maksimovich/Task3_Maksimovich/src/by/training/analyser/breakfastMenu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.tc.by/breakfastMenu" xmlns:tns="http://www.tc.by/breakfastMenu">

	<xs:element name="breakfast-menu">

		<xs:complexType>
			<xs:sequence>
				<xs:element name="food" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"></xs:element>
							<!-- нужно создать свой тип -->
							<xs:element name="price" type="tns:Price"></xs:element>
							<xs:element name="description" type="xs:string"></xs:element>
							<xs:element name="calories" type="xs:positiveInteger"></xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger"
							use="required"></xs:attribute>
						<!-- нужно создать перечисление -->
						<xs:attribute name="status" type="tns:Status" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="Price">
		<xs:restriction base="xs:string">
			<xs:pattern value="$\d+.\d{2}" />
		</xs:restriction>
	</xs:simpleType>


		<xs:simpleType name="Status">
			<xs:restriction base="xs:boolean">
				<xs:pattern value="true|false" />
				<!-- <xs:restriction base="xs:string"> <xs:enumeration value="true" /> 
					<xs:enumeration value="false" /> -->
			</xs:restriction>
		</xs:simpleType>

</xs:schema>

=== oleggye/Java11_16_Maksimovich/Task3_Maksimovich/src/by/training/analyser/breakFastMenu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<tc:breakfast-menu xmlns:tc="http://www.tc.by/breakfastMenu"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tc.by/breakfastMenu breakfastMenu.xsd">

	<food id="1" status="true">
		<name>Belgian Waffles</name>
		<price>$5.95</price>
		<description>
			two of our famous Belgian Waffles with plenty of real
			maple syrup
		</description>
		<calories>650</calories>
	</food>

	<food id="2" status="false">
		<name>Strawberry Belgian Waffles</name>
		<price>$7.95</price>
		<description>
			light Belgian waffles covered with strawberries and
			whipped cream
		</description>
		<calories>650</calories>
	</food>

</tc:breakfast-menu>
