=== oleggye/Java11_16_Maksimovich/Task3_Maksimovich/src/by/training/analyser/notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.tc.by/notes" xmlns:tns="http://www.tc.by/notes">


	<xs:element name="notes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="note" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="to" type="xs:string" />
							<xs:element name="from" type="xs:string" />
							<xs:element name="heading" type="xs:string" />
							<xs:element name="body" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger"
							use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== oleggye/Java11_16_Maksimovich/Task3_Maksimovich/src/by/training/analyser/notes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<tc:notes xmlns:tc="http://www.tc.by/notes"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tc.by/notes notes.xsd">
	<note id="1">
		<to>Вася</to>
		<from>Света</from>
		<heading>Напо
		мина
		ние</heading>
		<body>Позвони мне завтра!</body>
	</note>
	<note id="2">
		<to>Петя</to>
		<from>Маша</from>
		<heading>Важное напоминание</heading>
		<body/>
	</note>
</tc:notes>
